function createfigure(xdata1, ydata1, zdata1)
%CREATEFIGURE(xdata1, ydata1, zdata1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 04-Jan-2023 16:22:34

% Create figure
figure1 = figure('WindowState','maximized');

% Create subplot
subplot1 = subplot(1,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',subplot1);

% Create zlabel
zlabel('Contrast');

% Create ylabel
ylabel('Interval length [Number of values]');

% Create xlabel
xlabel('Interval start [%]');

view(subplot1,[-28.1436723717835 9.28370787499743]);
grid(subplot1,'on');
hold(subplot1,'off');
% Create subplot
subplot2 = subplot(1,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',subplot2);

% Create zlabel
zlabel('Contrast');

% Create ylabel
ylabel('Interval length [Number of values]');

% Create xlabel
xlabel('Interval start [%]');

view(subplot2,[0.363039399624753 90]);
grid(subplot2,'on');
hold(subplot2,'off');
% Create colorbar
colorbar(subplot2);

